name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Force deployment to DEV"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: PRD
    values:
      - None
      - DEV
      - TST
      - PRE
      - PRD  

trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - '*'

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: master
  pipelines:
    - pipeline: INFRA
      source: Defra.Trade.API.Infra Events.IDCOMS.GCEnricher
      trigger:
        branches:
          include:
            - '*'
        stages:
          - DEV

variables:
  APIName: Defra.Trade.Events.IDCOMS.GCEnricher

extends:
  template: /templates/basic-webapp-deploy-pipeline.yaml@PipelineCommon
  parameters:
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    deployToSecondary: ${{ parameters.deployToSecondary }}
    appName: $(APIName)
    appProject: TRA
    appType: 'functionApp'
    appInstanceNumber: $(nc-region-id)02
    scr: GH
    publishArguments: '--configuration Release'
    publishProject: '**/*Defra.Trade.Events.IDCOMS.GCEnricher.csproj'
    runHealthCheck: false
    appSettingsEnv:
      dev: '-AzureResourceGroupName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-resourcegroup)1001" -AzureServiceBusName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001" -ConfigurationServer:Uri "https://$(environment)TRDINFAC1001.azconfig.io" -FUNCTIONS_INPROC_NET8_ENABLED "1"'
      snd: '-AzureResourceGroupName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-resourcegroup)1001" -AzureServiceBusName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001" -ConfigurationServer:Uri "https://$(environment)TRDINFAC1001.azconfig.io" -FUNCTIONS_INPROC_NET8_ENABLED "1"' 
      tst: '-AzureResourceGroupName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-resourcegroup)1001" -AzureServiceBusName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001" -ConfigurationServer:Uri "https://$(environment)TRDINFAC1001.azconfig.io" -FUNCTIONS_INPROC_NET8_ENABLED "1"'
      pre: '-AzureResourceGroupName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-resourcegroup)1001" -AzureServiceBusName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001" -ConfigurationServer:Uri "https://$(environment)TRDINFAC1001.azconfig.io" -FUNCTIONS_INPROC_NET8_ENABLED "1"'
      prd: '-AzureResourceGroupName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-resourcegroup)1001" -AzureServiceBusName "$(Environment.Name)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001" -ConfigurationServer:Uri "https://$(environment)TRDINFAC1001.azconfig.io" -FUNCTIONS_INPROC_NET8_ENABLED "1"'
